[project]
name = "mvp"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "polars>=1.30.0",
    "sodapy>=2.2.0",
]

[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
]
